// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDe_qlt8NvT3_IffmFKV6g2Yzn2_11rg8Q',
    appId: '1:228235080735:web:5b62f3a125292e810b512a',
    messagingSenderId: '228235080735',
    projectId: 'ecommerce-56931',
    authDomain: 'ecommerce-56931.firebaseapp.com',
    storageBucket: 'ecommerce-56931.appspot.com',
    measurementId: 'G-6JJWDW54B7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBr0nxbI0j-qW4nyKbAFm-OTNsuxfnMri8',
    appId: '1:228235080735:android:a60cbd616c068e590b512a',
    messagingSenderId: '228235080735',
    projectId: 'ecommerce-56931',
    storageBucket: 'ecommerce-56931.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAz2dQU76aEU7lsFB-CULnHsyBDUWhbO9w',
    appId: '1:228235080735:ios:0ce1b508345d4de20b512a',
    messagingSenderId: '228235080735',
    projectId: 'ecommerce-56931',
    storageBucket: 'ecommerce-56931.appspot.com',
    iosBundleId: 'com.example.amazon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAz2dQU76aEU7lsFB-CULnHsyBDUWhbO9w',
    appId: '1:228235080735:ios:0ce1b508345d4de20b512a',
    messagingSenderId: '228235080735',
    projectId: 'ecommerce-56931',
    storageBucket: 'ecommerce-56931.appspot.com',
    iosBundleId: 'com.example.amazon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDe_qlt8NvT3_IffmFKV6g2Yzn2_11rg8Q',
    appId: '1:228235080735:web:9be902a2b2cc62230b512a',
    messagingSenderId: '228235080735',
    projectId: 'ecommerce-56931',
    authDomain: 'ecommerce-56931.firebaseapp.com',
    storageBucket: 'ecommerce-56931.appspot.com',
    measurementId: 'G-XXBRVRGJ4J',
  );
}
